name: first workflow

on:
    workflow_dispatch:

jobs:
 firstjob:
     runs-on: self-hosted
     steps:
     - name: firstjob script
       shell: cmd
       run: echo Hello World!


 secondjob:     
      runs-on: ubuntu-latest
      steps:
      - name: secondjob script
        shell: bash
        run: |
             echo this is second job
             echo this is multiline job
